services:
  # Production backend - only override NODE_ENV
  backend:
    environment:
      - NODE_ENV=production

  # Production frontend - only add port mapping
  frontend:
    ports:
      - "8080:80" 