services:
  # Development backend - hot reload and dev build
  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./rbarros-backend:/app
      - /app/node_modules
    command: npm run dev

  # Development frontend - hot reload and dev build
  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./rbarros-frontend:/app
      - /app/node_modules
    command: npm run serve

volumes:
  mysql_data:
    driver: local 