services:
  database:
    image: mysql:8.0
    container_name: rbarros-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword123}
      MYSQL_DATABASE: ${DB_NAME:-rbarrosassurances}
      MYSQL_USER: ${DB_USER:-rbarros_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpassword123}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./rbarros-backend/database/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    networks:
      - rbarros-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-rootpassword123}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  rbarros-network:
    driver: bridge 