name: Docker Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy to production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /path/to/rbarros-deployment
            git pull origin main
            
            # Set environment variables from secrets
            export DB_HOST="${{ secrets.DB_HOST }}"
            export DB_USER="${{ secrets.DB_USER }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export DB_NAME="${{ secrets.DB_NAME }}"
            export SECRET_KEY="${{ secrets.SECRET_KEY }}"
            export SECRET_KEY_REFRESH_TOKEN="${{ secrets.SECRET_KEY_REFRESH_TOKEN }}"
            export SENDGRID_API_KEY="${{ secrets.SENDGRID_API_KEY }}"
            export WEBHOOK_SECRET="${{ secrets.WEBHOOK_SECRET }}"
            export MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}"
            export VUE_APP_API_URL="${{ secrets.VUE_APP_API_URL }}"
            
            # Deploy with Docker Compose
            make deploy-secrets
