name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            cd ~/rbarros-deployment
            
            # Check if .env file exists
            if [ ! -f .env ]; then
              echo "❌ Error: .env file not found in ~/rbarros-deployment"
              echo "Please create a .env file with the required environment variables"
              exit 1
            fi
            
            # Debug: Check if .env file is readable and show some info
            echo "✅ .env file found"
            echo "Environment file size: $(wc -c < .env) bytes"
            
            # key must be set in the .ssh/config file as github-rbarros-deploy
            git remote set-url origin git@github-rbarros-deploy:estiveljr/rbarros-deployment.git
            git pull --recurse-submodules
            
            # Stop containers
            sudo docker-compose -f docker-compose.prod.yml down
            
            # Start containers with .env file (docker-compose automatically reads .env)
            sudo docker-compose -f docker-compose.prod.yml up -d --build
            echo "✅ Deployment complete!"
