name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          envs: NODE_ENV,DB_HOST,DB_USER,DB_PASSWORD,DB_NAME,SECRET_KEY,SECRET_KEY_REFRESH_TOKEN,SENDGRID_API_KEY,WEBHOOK_SECRET,MYSQL_ROOT_PASSWORD,VUE_APP_API_URL
          script: |
            cd ~/rbarros-deployment
            git pull --recurse-submodules
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build
            echo "✅ Deployment complete!"
        env:
          NODE_ENV: production
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SECRET_KEY_REFRESH_TOKEN: ${{ secrets.SECRET_KEY_REFRESH_TOKEN }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
