name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            cd ~/rbarros-deployment
            
            # key must be set in the .ssh/config file as github-rbarros-deploy
            git remote set-url origin git@github-rbarros-deploy:estiveljr/rbarros-deployment.git
            git pull --recurse-submodules
            
            # Stop containers
            sudo docker-compose -f docker-compose.prod.yml down
            
            # Start containers with .env file (docker-compose automatically reads .env)
            sudo docker-compose -f docker-compose.prod.yml up -d --build
            echo "✅ Deployment complete!"
