name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          envs: NODE_ENV,DB_HOST,DB_USER,DB_PASSWORD,DB_NAME,SECRET_KEY,SECRET_KEY_REFRESH_TOKEN,SENDGRID_API_KEY,WEBHOOK_SECRET,MYSQL_ROOT_PASSWORD,VUE_APP_API_URL
          script: |
            cd ~/rbarros-deployment
            
            # Debug: Check if environment variables are already available
            echo "Checking environment variables:"
            echo "DB_USER is: $DB_USER"
            echo "SECRET_KEY is set: $([ -n "$SECRET_KEY" ] && echo "YES" || echo "NO")"
            
            # key must be set in the .ssh/config file as github-rbarros-deploy
            git remote set-url origin git@github-rbarros-deploy:estiveljr/rbarros-deployment.git
            git pull --recurse-submodules
            sudo -E make down-prod
            sudo -E make deploy-secrets
            echo "✅ Deployment complete!"

        env:
          NODE_ENV: production
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SECRET_KEY_REFRESH_TOKEN: ${{ secrets.SECRET_KEY_REFRESH_TOKEN }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
